### PR TITLE
drop params.pp and anchor, use hiera data and contain

### PR DESCRIPTION
**Pull request by Dan33l**
This permits to get default values documented into `REFERENCE.md`.

### CODE REVIEW

**Comment by Dan33l** [comment]
HUm i forgotten to update README.md. On the way ...

**Comment by Dan33l** [comment]
IMO the `CONTRIBUTING.md` file should be updated. At least since open an issue is not possible here.

**Comment by Dan33l** [comment]
The anchor pattern was a workaround with previous puppet versions.

**Comment by Dan33l** [comment]
@simmerz can you consider to review this PR ?

the goal is to have a module up to date with state of the art.

**Comment by Dan33l** [comment]
thank you.
when the updated module will be available on the forge ?
To follow [Semver](https://semver.org/), an update of major digit is needed.

**Comment by simmerz** [comment]
Already done: https://forge.puppet.com/initforthe/yarn (v1.0.x -> v1.1.0)

**Comment by Dan33l** [comment]
@simmerz you released a module 1.x :
https://github.com/initforthe/puppet-yarn/blob/master/metadata.json#L3

The CHANGELOG.md is not updated

**Comment by simmerz** [comment]
I'm of the opinion that this is a minor version release. There are some breaking changes, but at v1.x that's ok.

As to the changelog being updated, that's not something that's been done before, and I've taken on a shoulder of responsibility to continue development of the module in the first place as the original maintainer left the project unmaintained for several years.

Realistically, PRs should contain entries to the changelog in an "Unreleased" section (the changelog is empty right now and always has been), which then get turned into the latest release. All that can be done, but hasn't to date.

**Pull request merged**
