### PR TITLE
[change_key_server] Change keyserver, because pgp.mit.edu is unreliable.

### PR DESCRIPTION
**Pull request by func0der**
Because of reasons: https://github.com/puppetlabs/puppetlabs-apt/commit/1e1e4b566ed2b7ce7c822365e32b26974afbc756

 :)

### CODE REVIEW

**Comment by func0der** [comment]
Thanks :)

**Comment by jozsi** [comment]
Any plans on releasing this to Puppet Forge?

PS: We could just ignore the server key cause the `apt` package will default it (to `keyserver.ubuntu.com` currently)

**Comment by simmerz** [comment]
@jozsi just pushed a new build up to the forge

**Comment by jozsi** [comment]
Thank you, @simmerz! Unfrotunately, that explicit keyserver is not very reliable either:
```
==> docker: Error: Execution of '/usr/bin/apt-key adv --no-tty --keyserver hkps.pool.sks-keyservers.net --recv-keys 72ECF46A56B4AD39C907BBB71646B01B86E50310' returned 2: Warning: apt-key output should not be parsed (stdout is not a terminal)
==> docker: Executing: /tmp/apt-key-gpghome.iA7tvYfTNN/gpg.1.sh --no-tty --keyserver hkps.pool.sks-keyservers.net --recv-keys 72ECF46A56B4AD39C907BBB71646B01B86E50310
==> docker: gpg: keyserver receive failed: Cannot assign requested address
==> docker: Error: /Stage[main]/Yarn::Repo/Apt::Source[yarn]/Apt::Key[Add key: 72ECF46A56B4AD39C907BBB71646B01B86E50310 from Apt::Source yarn]/Apt_key[Add key: 72ECF46A56B4AD39C907BBB71646B01B86E50310 from Apt::Source yarn]/ensure: change from 'absent' to 'present' failed: Execution of '/usr/bin/apt-key adv --no-tty --keyserver hkps.pool.sks-keyservers.net --recv-keys 72ECF46A56B4AD39C907BBB71646B01B86E50310' returned 2: Warning: apt-key output should not be parsed (stdout is not a terminal)
==> docker: Executing: /tmp/apt-key-gpghome.iA7tvYfTNN/gpg.1.sh --no-tty --keyserver hkps.pool.sks-keyservers.net --recv-keys 72ECF46A56B4AD39C907BBB71646B01B86E50310
==> docker: gpg: keyserver receive failed: Cannot assign requested address
```

See the PS in my previous comment for a potential idea.

**Comment by simmerz** [comment]
Do you want to submit a new PR and I'll get it merged?

**Comment by jozsi** [comment]
Sure @simmerz , done in #3. Thanks!

**Comment by func0der** [comment]
Thanks :)

**Pull request merged**
